Another docker install approach

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -84,11 +84,14 @@ jobs:
                       conan_data
                   key: conan-${{ matrix.worker }}-${{ hashFiles('conanfile.txt') }}
 
-            - name: Setup docker (missing on MacOS)
-              if: matrix.os == 'macos'
+            - name: Setup docker for linux builds on macOS
+              if: matrix.platform == 'linux-arm64'
               run: |
-                  brew install docker
-                  colima start
+                  HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask docker
+                  sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
+                  open -a /Applications/Docker.app --args --unattended --accept-license
+                  echo "We are waiting for Docker to be up and running. It can take over 2 minutes..."
+                  while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
 
             - name: Setup Python
               if: matrix.host == 'gh'
